#!/usr/bin/env perl
use strict;
use warnings;
use 5.014;

use Future;
use Path::Class;
use File::Which qw(which);
use Cwd qw(getcwd);
use App::Multigit;

sub usage;

my $cmd = shift or say usage and exit 1;

if ($cmd eq 'help') {
    # mg help is just usage
    $cmd = shift or say usage and exit 0;

    @ARGV = '--help';
}
else {
    # init cannot know the mg_parent because there might not be one yet
    unshift @ARGV, '--workdir', App::Multigit::mg_parent
        unless $cmd eq 'init';
}

my $mg_cmd = which("mg-$cmd") // die "$cmd is not an mg command.\n";

exec $mg_cmd, @ARGV
    or die "Failed to exec $mg_cmd: $!";

sub usage {
<<EOU;
Usage:
    mg [options] command [command-options]
    mg help [command]
EOU
}
