#!/usr/bin/env perl
use strict;
use warnings;
use 5.014;

use Getopt::Long qw(:config gnu_getopt);
use App::Multigit;
use Future;
use Cwd qw(getcwd);
use curry;

my $workdir;
GetOptions(
    'help|h' => sub {
        say usage();
        exit 0;
    },
);

my $config = shift;

if ($config) {
    if ($config =~ m{://}) {
        mirror($config, mgconfig);
    }
    else {
        copy($config, mgconfig);
    }
}

if (eval { mg_parent }) {
    my $all_repositories = all_repositories;

    for my $config (values %$all_repositories) {
        next if -e $config->{dir};

        system qw(git clone), $config->{url};
    }
}

App::Multigit::init(getcwd);

=head1 SYNOPSIS

    mg init

Creates or updates the .mgconfig in the current working directory by iterating
the subdirectories and assuming they are git repos.

Except for the dir keys, all existing configuration will be maintained, if
possible.
