#!/usr/bin/env perl
use strict;
use warnings;
use 5.014;

use Getopt::Long qw(:config gnu_getopt pass_through);
use App::Multigit;
use Future;
use Cwd qw(getcwd);
use curry;

my $workdir;
GetOptions(
    'help|h' => sub {
        say usage();
        exit 0;
    },
);

App::Multigit::init(getcwd);

sub usage() {
<<'EOU'
Usage:
    mg init

Creates or updates the .mgconfig in the current working directory by iterating
the subdirectories and assuming they are git repos.

Except for the dir keys, all existing configuration will be maintained, if
possible.
EOU
}
