#!/usr/bin/env perl
use strict;
use warnings;
use 5.014;

use App::Multigit;
use App::Multigit::Script;

say App::Multigit::mg_parent();

sub usage() {
<<EOU
Usage:
    
    mg root

Reports the closest parent directory with a .mgconfig file in it.
EOU
}
